### ISSUE TITLE
MVP FEATURES

### ISSUE THREAD

**Issue by nhlmg93** [nhlmg93/karussell#1]
FEATURES:

- [x]  Can aggregate pictures(png) from a given directory #2 
- [ ]  Displays a picture from directory randomly #3 
- [x]  can rotate through pictures on some interval #4
